theme: jekyll-theme-minimal

# Name of site
title: Hi! I'm Jonathan.

# Short bio
description:  

# Other links for the footer
social-links:
    email: jon.twk@gmail.com
    github: jtanwk
    linkedin: jtanwk
    twitter: jtanwk
