theme: jekyll-theme-minimal

# Name of site
title: hi! i'm jonathan.

# Short bio
description: M.S. Computational Analysis & Public Policy (CAPP) student at UChicago. 

# Other links for the footer
social-links:
    email: jon.twk@gmail.com
    github: jtanwk
    linkedin: jtanwk
    twitter: jtanwk
